id: P4BCD4A9C
initial_creation_type: ocr
source_metadata:
  volumes:
    f60aba2c2af144bfabf4c778b2849da7:
      base_file: v114.txt
      image_group_id: I1PD95959
      title: ''
      total_pages: 1872
      volume_number: 114
